"""Helpers for building QT framework libraries."""

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//:qt_tools.bzl", "moc_gen")

def qt_internal_library(
        name = "",
        srcs = [],
        tags = [],
        platform_srcs = [],
        moc_hdrs = [],
        moc_opts = [],
        rcc_srcs = [],
        resource_srcs = [],
        uic_srcs = [],
        deps = [],
        defines = [],
        cxxopts = [],
        conlyopts = [],
        copts = [],
        linkopts = [],
        linkstatic = False,
        includes = [],
        compatible_with = [],
        qmlcachegen_options = [],
        qmlcachegen_resources = [],
        qmlcachegen_qml_loader_file_list = None,
        qmlcachegen_resource_paths = [],
        hdrs = [],
        alwayslink = 0,
        visibility = [],
        additional_linker_inputs = [],
        local_defines = [],
        outdir_suffix = ""):
    """Rule to build a QT framework library.

    qt_internal_library generates the cc_library rule to build an internal
    library by running moc over the specified headers and sources.

    These rules should be created by looking at the corresponding Makefiles
    generated by qmake after running configure. qmake runs moc and uic over the
    appropriate files (determined by grepping for the Q_OBJECT macro) and
    determines dependencies by grepping for #include statements; its
    determinations should be used in these rules.

    In particular: 1. moc_hdrs should be populated from the
    compiler_moc_header_make_all target in the Makefile.  2. moc_srcs should be
    populated from the compiler_moc_source_make_all target in the Makefile.  3.
    srcs should be populated from the SOURCES var in the Makefile.

    We can't just merge moc_srcs and srcs because certain files need to be moc'd,
    but should not be built because they are #include'd into other cpp files.
    That's why moc outputs need to be explicitly included in srcs.

    Args:
      name: name of the target library.
      srcs: all source files; passed to cc_library.
      tags: passed to cc_library.
      platform_srcs: platform-specific source files; passed to cc_library without inspection.
      moc_hdrs: list of header files to pass through moc tool.
      moc_opts: extra flags passed to moc tool.
      rcc_srcs: list of .qrc files to pass through rcc tool.
      resource_srcs: list of files that will be added in some .qrc file.
      uic_srcs: list of .ui files to pass through uic tool.
      deps: passed to cc_library
      defines: passed to cc_library.
      cxxopts: passed to cc_library.
      conlyopts: passed to cc_library
      copts: passed to cc_library.
      linkopts: passed to cc_library.
      linkstatic: passed to cc_library.
      includes: passed to cc_library.
      compatible_with: passed to cc_library.
      qmlcachegen_options: options to qmlcachegen. These values are defined in the build.make file.
      qmlcachegen_resources: arguments to qmlcachegen --resource. These values are defined in the build.make file.
      qmlcachegen_qml_loader_file_list: arguments to qmlcacheghen --resource-name. The value is defined in the build.make file.
      qmlcachegen_resource_paths: arguments to qmlcachegen --resource-path, each should start with
                                  /qt-project.org/imports/.
                                  These are not real paths, if you want to change it, you may need
                                  to change the content in the 'qmlcachegen_qml_loader_file_list'.
                                  These values are defined in the build.make file.
      hdrs: all header files; passed to cc_library.
      alwayslink: passed to cc_library.
      visibility: passed to cc_library.
      additional_linker_inputs: passed to cc_library.
      local_defines: passed to cc_library.
      outdir_suffix: Optional suffix for internal rules and generated files.
    """

    # We'll try to figure out what the first directory is by looking at the
    # first moc_hdr we find. If we can't find one, we'll just make something up
    # based on the source files that begins with qt.
    generated_out_dir = None
    if srcs and type(srcs) == type([]):
        for src in srcs:
            if ".moc" in src:
                generated_out_dir = src[:src.find(".moc")]
                break

        # That failed, if it's a plugin, try to guess based on where the
        # plugin's main file is.
        if not generated_out_dir:
            for src in srcs:
                if "plugins" in src and "main" in src[src.rfind("/"):]:
                    generated_out_dir = src[:src.rfind("main")]

    if not generated_out_dir:
        for src in srcs:
            first_dir = src[:src.find("/")]
            if first_dir.startswith("qtbase") and first_dir.endswith("6.9.1"):
                generated_out_dir = "%s/src/%s/" % (first_dir, name)

    if not generated_out_dir:
        # Ehh, just use something.
        fail("%s does not look to be a qt library" % name)

    moc_out_dir = generated_out_dir + ".moc/" + outdir_suffix
    rcc_out_dir = generated_out_dir + ".rcc/" + outdir_suffix
    uic_out_dir = generated_out_dir + ".uic/" + outdir_suffix
    qmlcachegen_out_dir = generated_out_dir + ".qmlcache/" + outdir_suffix

    moc_genrules = []
    moc_files = []
    moc_src_files = []  # From headers: compiled as separate translation units
    moc_textual_files = []  # From .cpp: included via #include "foo.moc"
    for src in moc_hdrs:
        rulename = "MOC_" + outdir_suffix.replace("/", "_") + "_" + src.replace("/", "_").replace(":", "_")

        last_slash = src.rindex("/")
        filename = src[last_slash + 1:]

        if filename[-1:] == "h":
            dest = moc_out_dir + "moc_" + filename[:-2] + ".cpp"
            moc_src_files.append(dest)
        elif filename[-3:] == "cpp":
            dest = moc_out_dir + filename[:-4] + ".moc"
            moc_textual_files.append(dest)
        else:
            fail("Unsupported extension for %s" % src)

        moc_genrules.append({
            "name": rulename,
            "source": src,
            "output": dest,
        })

        moc_files.append(dest)

    # Make a dummy library that lets us easily pass defines/copts/includes
    # along with the deps to the moc rule.
    internal_deps_lib_name = name + "_internal_deps"
    cc_library(
        name = internal_deps_lib_name,
        compatible_with = compatible_with,
        copts = copts,
        cxxopts = cxxopts,
        conlyopts = conlyopts,
        defines = defines + local_defines,
        includes = includes,
        textual_hdrs = hdrs,
    )

    for moc_genrule in moc_genrules:
        moc_gen(
            name = moc_genrule["name"],
            src = moc_genrule["source"],
            out = moc_genrule["output"],
            copts = copts,
            moc_opts = moc_opts,
            deps = deps + [":" + internal_deps_lib_name],
            compatible_with = compatible_with,
            resource_srcs = hdrs + resource_srcs,
            rewrite_includes = False,
            show_warnings = True,
            transitive_deps = True,
        )

    # Run rcc on any .qrc files
    alwayslink_srcs = []
    for src in rcc_srcs:
        rulename = "RCC_" + outdir_suffix.replace("/", "_") + "_" + src.replace("/", "_").replace(":", "_")

        last_slash = src.rindex("/")
        filename = src[last_slash + 1:]
        qrc_name = filename[:filename.rfind(".")]
        dest = rcc_out_dir + "qrc_" + qrc_name + ".cpp"

        native.genrule(
            name = rulename,
            srcs = [src] + resource_srcs,
            outs = [dest],
            tools = [":rcc"],
            # By default, 'rcc' encodes timestamp of the source, which
            # is meaningless on Forge and leads to non-deterministic builds.
            # Override the timestamp with 1ms since epoch (timestamp can't be 0).
            cmd = "QT_RCC_SOURCE_DATE_OVERRIDE=1 " +
                  "$(location :rcc) --name %s $(execpath %s) -o $@" % (qrc_name, src),
            compatible_with = compatible_with,
        )
        alwayslink_srcs.append(dest)

    uic_files = []
    for src in uic_srcs:
        rulename = "UIC_" + outdir_suffix.replace("/", "_") + "_" + src.replace("/", "_").replace(":", "_")

        last_slash = src.rindex("/")
        filename = src[last_slash + 1:]
        ui_name = filename[:filename.rfind(".")]
        dest = uic_out_dir + "ui_" + ui_name + ".h"

        native.genrule(
            name = rulename,
            srcs = [src],
            outs = [dest],
            tools = [":uic"],
            cmd = "$(location :uic) $< -o $@",
            compatible_with = compatible_with,
        )
        uic_files.append(dest)

    # If we were given qmlcachegen_qml_loader_file_list, generate the qmlcache code.
    if qmlcachegen_qml_loader_file_list:
        dest = qmlcachegen_out_dir + "qmlcache_loader.cpp"
        last_slash = qmlcachegen_qml_loader_file_list.rindex("/")
        resource_name = qmlcachegen_qml_loader_file_list[last_slash + 1:].split("_")[0]
        resource_name = "qmlcache_" + resource_name
        cmd = "$(location :qmlcachegen) --resource-name %s -o $@ @$<" % (
            resource_name
        )

        native.genrule(
            name = name + "_qmlcachegen_loader",
            srcs = [qmlcachegen_qml_loader_file_list],
            outs = [dest],
            tools = [":qmlcachegen"] + qmlcachegen_resources,
            cmd = cmd,
            compatible_with = compatible_with,
        )
        alwayslink_srcs.append(dest)

    # Build the cache for each of the qml files listed.
    qmlcachegen_common_option = ""
    for option in qmlcachegen_options:
        qmlcachegen_common_option += " %s" % option
    for resource in qmlcachegen_resources:
        qmlcachegen_common_option += " --resource $(location %s)" % resource
    PATH_PREFIX = "/qt-project.org/imports/"
    for path in qmlcachegen_resource_paths:
        if not path.startswith(PATH_PREFIX):
            continue
        rulename = "QMLCACHEGEN_" + outdir_suffix.replace("/", "_") + "_" + path.replace("/", "_").replace(":", "_")
        last_slash = path.rindex("/")
        filename = path[len(PATH_PREFIX):]
        filename = filename[filename.find("/") + 1:]
        dest = qmlcachegen_out_dir + filename.replace(".", "_") + ".cpp"
        qmlcachegen_option = (" --resource-path %s " % path) + qmlcachegen_common_option
        cmd = "$(location :qmlcachegen)%s --bare -o $@ $<" % qmlcachegen_option
        native.genrule(
            name = rulename,
            srcs = [generated_out_dir + filename],
            outs = [dest],
            tools = [":qmlcachegen"] + qmlcachegen_resources,
            cmd = cmd,
            compatible_with = compatible_with,
        )
        alwayslink_srcs.append(dest)
    alwayslink_deps = []
    if alwayslink_srcs:
        alwayslink_name = "_" + name + "_alwayslink"
        alwayslink_deps = [":" + alwayslink_name]
        cc_library(
            name = alwayslink_name,
            alwayslink = 1,
            compatible_with = compatible_with,
            copts = copts,
            deps = deps,
            includes = includes,
            linkopts = linkopts,
            linkstatic = linkstatic,
            additional_linker_inputs = additional_linker_inputs,
            srcs = alwayslink_srcs,
            tags = tags,
        )

    cc_library(
        name = name,
        srcs = srcs + platform_srcs,
        tags = tags,
        deps = deps + alwayslink_deps,
        defines = defines,
        copts = copts,
        cxxopts = cxxopts,
        conlyopts = conlyopts,
        linkopts = linkopts,
        linkstatic = linkstatic,
        includes = includes + [moc_out_dir, uic_out_dir],
        hdrs = hdrs,
        textual_hdrs = moc_files + uic_files,
        compatible_with = compatible_with,
        visibility = visibility,
        alwayslink = alwayslink,
        additional_linker_inputs = additional_linker_inputs,
        local_defines = local_defines,
    )

def qt_static_plugin(
        name,
        plugin_class_name,
        hdrs = [],
        compatible_with = [],
        **kwargs):
    """Helper function that generates an extra cc file to instantiate the plugin.

    Args:
      name: passed to qt_internal_library.
      plugin_class_name: The C++ class that will be passed to Q_IMPORT_PLUGIN.
      hdrs: passed to qt_internal_library.
      compatible_with: passed to qt_internal_library.
      **kwargs: passed to qt_internal_library.
    """
    qt_internal_library(
        name = name + "_impl",
        hdrs = hdrs,
        compatible_with = compatible_with,
        **kwargs
    )
    native.genrule(
        name = name + "_source_gen",
        outs = [name + ".cc"],
        compatible_with = compatible_with,
        cmd = "echo '#include <QtPlugin>\nQ_IMPORT_PLUGIN(%s);' > $@" % plugin_class_name,
    )
    cc_library(
        name = name,
        compatible_with = compatible_with,
        copts = ["-DQT_STATICPLUGIN"],
        deps = [
            ":" + name + "_impl",
            "//qt_source:core",
        ],
        hdrs = hdrs,
        srcs = [name + ".cc"],
        visibility = ["//visibility:public"],
        alwayslink = 1,
    )

def qt_cc_inc_library(name, qt_version, deps = [], compatible_with = [], linkopts = []):
    """A public qt api library with headers that can be reached by including qt_source/qt.

    Combines the given deps with the versionless qt headers.

    Args:
      name: passed to cc_library.
      qt_version: decimal separated string containing the qt version.
      compatible_with: passed to cc_library.
      deps: passed to cc_library.
      compatible_with: passed to cc_library.
      linkopts: passed to cc_library.
    """
    qt_version_underscore = qt_version.replace(".", "_")
    cc_library(
        name = name,
        hdrs = [":_" + qt_version_underscore + "_inc", ":_" + qt_version_underscore + "_hdrs"],
        deps = deps + [":_" + qt_version_underscore],
        compatible_with = compatible_with,
        linkopts = linkopts,
        # instruct go/build-cleaner to pretend this target does not define main()
        # so that it can be removed if unused.
        tags = ["cc_main=ignore"],
    )
